// Write a font stylesheet holding only the families a route asks for.
//
// assets/css/fonts.css is the full cache of every family either route has ever
// used: 125 @font-face rules and 70 kB, most of it Arabic faces and display
// scripts the English portrait route no longer touches now that its display
// lettering comes from the source artwork. The browser only downloads the files
// it needs either way, but the stylesheet itself is transferred and parsed in
// full, so each route gets its own list.
//
// Run after scripts/vendor-fonts.mjs, which refreshes fonts.css:
//   node scripts/subset-fonts.mjs
import { readFileSync, writeFileSync } from 'node:fs';
import { resolve } from 'node:path';

const root = resolve(import.meta.dirname, '..');
const source = readFileSync(resolve(root, 'assets/css/fonts.css'), 'utf8');

// The families named by assets/css/reference-source.css and portrait-site.css.
// Everything else on the English route is either system type (Impact and Arial
// in the countdown) or artwork.
const routes = [
  { output: 'assets/css/fonts-portrait.css', families: ['Ballet', 'Cormorant Garamond', 'Montserrat'] },
];

for (const { output, families } of routes) {
  const kept = [];
  for (const block of source.match(/@font-face\s*\{[^}]*\}/g) || []) {
    const family = block.match(/font-family:\s*'([^']+)'/)?.[1];
    if (families.includes(family)) kept.push(block);
  }
  const missing = families.filter(family => !kept.some(block => block.includes(`'${family}'`)));
  if (missing.length) throw new Error(`No faces found for: ${missing.join(', ')}`);
  const css = `/* Generated by scripts/subset-fonts.mjs from assets/css/fonts.css.\n`
    + `   Families: ${families.join(', ')}. Licences live beside the WOFF2 files\n`
    + `   in assets/fonts/. Do not edit by hand. */\n${kept.join('\n')}\n`;
  writeFileSync(resolve(root, output), css);
  console.log(`${output}: ${kept.length} of ${(source.match(/@font-face/g) || []).length} faces, `
    + `${source.length} → ${css.length} bytes`);
}
